title: "Studio Upleft"

url: "http://upleft.com"

sass:
    sass_dir: /r/css/_scss/

collections:
  work:
    title: Work
    output: true
  categories:
    title: Categories
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "project"

exclude: [Gemfile,Gemfile.lock]

markdown: kramdown
highlighter: rouge